-- MySQL Script generated by MySQL Workbench
-- Tue Feb  6 19:58:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema modelofinal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelofinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelofinal` DEFAULT CHARACTER SET utf8 ;
USE `modelofinal` ;

-- -----------------------------------------------------
-- Table `modelofinal`.`CAMION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`CAMION` (
  `idCamion` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `PATENTE` VARCHAR(6) NULL,
  `MotorNumero` VARCHAR(17) NULL,
  `ChasisNumero` VARCHAR(17) NULL,
  PRIMARY KEY (`idCamion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`CATEGORIA_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`CATEGORIA_EMPLEADO` (
  `idCategoriaEmpleado` INT NOT NULL AUTO_INCREMENT,
  `NombreCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoriaEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`PROVINCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`PROVINCIA` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `NombreProvincia` VARCHAR(45) NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`LOCALIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`LOCALIDAD` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `NombreLocalidad` VARCHAR(45) NULL,
  `PROVINCIA_idProvincia` INT NOT NULL,
  PRIMARY KEY (`idLocalidad`, `PROVINCIA_idProvincia`),
  INDEX `fk_LOCALIDAD_PROVINCIA1_idx` (`PROVINCIA_idProvincia` ASC),
  CONSTRAINT `fk_LOCALIDAD_PROVINCIA1`
    FOREIGN KEY (`PROVINCIA_idProvincia`)
    REFERENCES `modelofinal`.`PROVINCIA` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`DOMICILIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`DOMICILIO` (
  `idDomicilio` INT NOT NULL AUTO_INCREMENT,
  `LOCALIDAD_idLocalidad` INT NOT NULL,
  `Calle` VARCHAR(45) NULL,
  `Numero` VARCHAR(45) NULL,
  PRIMARY KEY (`idDomicilio`, `LOCALIDAD_idLocalidad`),
  INDEX `fk_DOMICILIO_LOCALIDAD1_idx` (`LOCALIDAD_idLocalidad` ASC),
  CONSTRAINT `fk_DOMICILIO_LOCALIDAD1`
    FOREIGN KEY (`LOCALIDAD_idLocalidad`)
    REFERENCES `modelofinal`.`LOCALIDAD` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`EMPLEADO` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `CUIT` VARCHAR(13) NULL,
  `CATEGORIA_EMPLEADO_idCategoriaEmpleado` INT NOT NULL,
  `hijos` INT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `FechaNacimiento` DATE NULL,
  `DOMICILIO_idDomicilio` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`, `CATEGORIA_EMPLEADO_idCategoriaEmpleado`, `DOMICILIO_idDomicilio`),
  INDEX `fk_EMPLEADO_CATEGORIA_EMPLEADO1_idx` (`CATEGORIA_EMPLEADO_idCategoriaEmpleado` ASC),
  INDEX `fk_EMPLEADO_DOMICILIO1_idx` (`DOMICILIO_idDomicilio` ASC),
  CONSTRAINT `fk_EMPLEADO_CATEGORIA_EMPLEADO1`
    FOREIGN KEY (`CATEGORIA_EMPLEADO_idCategoriaEmpleado`)
    REFERENCES `modelofinal`.`CATEGORIA_EMPLEADO` (`idCategoriaEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_DOMICILIO1`
    FOREIGN KEY (`DOMICILIO_idDomicilio`)
    REFERENCES `modelofinal`.`DOMICILIO` (`idDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `modelofinal`.`FINCA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`FINCA` (
  `idFinca` INT NOT NULL AUTO_INCREMENT,
  `coordenada` POINT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idFinca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`INGENIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`INGENIO` (
  `idIngenio` INT NOT NULL AUTO_INCREMENT,
  `coordenada` POINT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Arranque` DOUBLE NULL,
  `Tarifa` DOUBLE NULL,
  PRIMARY KEY (`idIngenio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`ORIGEN_DESTINO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`ORIGEN_DESTINO` (
  `idOrigen_Destino` INT NOT NULL AUTO_INCREMENT,
  `DistanciaKM` FLOAT NULL,
  `FINCA_idFinca` INT NOT NULL,
  `INGENIO_idIngenio` INT NOT NULL,
  PRIMARY KEY (`idOrigen_Destino`, `FINCA_idFinca`, `INGENIO_idIngenio`),
  INDEX `fk_ORIGEN_DESTINO_FINCA1_idx` (`FINCA_idFinca` ASC),
  INDEX `fk_ORIGEN_DESTINO_INGENIO1_idx` (`INGENIO_idIngenio` ASC),
  CONSTRAINT `fk_ORIGEN_DESTINO_FINCA1`
    FOREIGN KEY (`FINCA_idFinca`)
    REFERENCES `modelofinal`.`FINCA` (`idFinca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORIGEN_DESTINO_INGENIO1`
    FOREIGN KEY (`INGENIO_idIngenio`)
    REFERENCES `modelofinal`.`INGENIO` (`idIngenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `CUIT` VARCHAR(45) NULL,
  `DOMICILIO_idDomicilio` INT NOT NULL,
  PRIMARY KEY (`idCLIENTE`, `DOMICILIO_idDomicilio`),
  INDEX `fk_CLIENTE_DOMICILIO1_idx` (`DOMICILIO_idDomicilio` ASC),
  CONSTRAINT `fk_CLIENTE_DOMICILIO1`
    FOREIGN KEY (`DOMICILIO_idDomicilio`)
    REFERENCES `modelofinal`.`DOMICILIO` (`idDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`FACTURA_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`FACTURA_VENTA` (
  `idFACTURA_VENTA` INT NOT NULL AUTO_INCREMENT,
  `CUIT` VARCHAR(45) NULL,
  `FechaEmisión` DATE NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idFACTURA_VENTA`, `CLIENTE_idCLIENTE`),
  INDEX `fk_FACTURA_VENTA_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC),
  CONSTRAINT `fk_FACTURA_VENTA_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `modelofinal`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`VIAJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`VIAJE` (
  `idRemito` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `HoraEntrada` TIME NULL,
  `Bruto` DOUBLE NULL,
  `Tara` DOUBLE NULL,
  `Origen_Destino_idOrigen_Destino` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `CAMION_idCamion` INT NOT NULL,
  `FACTURA_VENTA_idFACTURA_VENTA` INT NOT NULL,
  PRIMARY KEY (`idRemito`, `Origen_Destino_idOrigen_Destino`, `Empleado_idEmpleado`, `CAMION_idCamion`, `FACTURA_VENTA_idFACTURA_VENTA`),
  INDEX `fk_Remito_Origen_Destino1_idx` (`Origen_Destino_idOrigen_Destino` ASC),
  INDEX `fk_Remito_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  INDEX `fk_REMITO_CAMION1_idx` (`CAMION_idCamion` ASC),
  INDEX `fk_VIAJE_FACTURA_VENTA1_idx` (`FACTURA_VENTA_idFACTURA_VENTA` ASC),
  CONSTRAINT `fk_Remito_Origen_Destino1`
    FOREIGN KEY (`Origen_Destino_idOrigen_Destino`)
    REFERENCES `modelofinal`.`ORIGEN_DESTINO` (`idOrigen_Destino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Remito_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `modelofinal`.`EMPLEADO` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REMITO_CAMION1`
    FOREIGN KEY (`CAMION_idCamion`)
    REFERENCES `modelofinal`.`CAMION` (`idCamion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIAJE_FACTURA_VENTA1`
    FOREIGN KEY (`FACTURA_VENTA_idFACTURA_VENTA`)
    REFERENCES `modelofinal`.`FACTURA_VENTA` (`idFACTURA_VENTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`PROVEEDOR` (
  `idPROVEEDOR` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `CUIT` VARCHAR(13) NULL,
  `DOMICILIO_idDomicilio` INT NOT NULL,
  PRIMARY KEY (`idPROVEEDOR`, `DOMICILIO_idDomicilio`),
  INDEX `fk_PROVEEDOR_DOMICILIO1_idx` (`DOMICILIO_idDomicilio` ASC),
  CONSTRAINT `fk_PROVEEDOR_DOMICILIO1`
    FOREIGN KEY (`DOMICILIO_idDomicilio`)
    REFERENCES `modelofinal`.`DOMICILIO` (`idDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`COMPRA_ARTICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`COMPRA_ARTICULO` (
  `idFacturaCompraArticulo` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `Total` DOUBLE NULL,
  `PROVEEDOR_idPROVEEDOR` INT NOT NULL,
  PRIMARY KEY (`idFacturaCompraArticulo`, `PROVEEDOR_idPROVEEDOR`),
  INDEX `fk_COMPRA_ARTICULO_PROVEEDOR1_idx` (`PROVEEDOR_idPROVEEDOR` ASC),
  CONSTRAINT `fk_COMPRA_ARTICULO_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_idPROVEEDOR`)
    REFERENCES `modelofinal`.`PROVEEDOR` (`idPROVEEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`CATEGORIA_ARTICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`CATEGORIA_ARTICULO` (
  `idCategoriaArticulo` INT NOT NULL AUTO_INCREMENT,
  `NombreCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoriaArticulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`ARTICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`ARTICULO` (
  `idArticulo` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(20) NULL,
  `Modelo` VARCHAR(20) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `CATEGORIA_ARTICULO_idCategoriaArticulo` INT NOT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`idArticulo`, `CATEGORIA_ARTICULO_idCategoriaArticulo`),
  INDEX `fk_ARTICULO_CATEGORIA_ARTICULO1_idx` (`CATEGORIA_ARTICULO_idCategoriaArticulo` ASC),
  CONSTRAINT `fk_ARTICULO_CATEGORIA_ARTICULO1`
    FOREIGN KEY (`CATEGORIA_ARTICULO_idCategoriaArticulo`)
    REFERENCES `modelofinal`.`CATEGORIA_ARTICULO` (`idCategoriaArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`DETALLE_COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`DETALLE_COMPRA` (
  `idCompraArticulo` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NULL,
  `PrecioUnitario` DOUBLE NULL,
  `Articulo_idArticulo` INT NOT NULL,
  `FacturaCompraArticulo_idFacturaCompraArticulo` INT NOT NULL,
  PRIMARY KEY (`idCompraArticulo`, `Articulo_idArticulo`, `FacturaCompraArticulo_idFacturaCompraArticulo`),
  INDEX `fk_CompraArticulo_Articulo1_idx` (`Articulo_idArticulo` ASC),
  INDEX `fk_CompraArticulo_FacturaCompraArticulo1_idx` (`FacturaCompraArticulo_idFacturaCompraArticulo` ASC),
  CONSTRAINT `fk_CompraArticulo_Articulo1`
    FOREIGN KEY (`Articulo_idArticulo`)
    REFERENCES `modelofinal`.`ARTICULO` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CompraArticulo_FacturaCompraArticulo1`
    FOREIGN KEY (`FacturaCompraArticulo_idFacturaCompraArticulo`)
    REFERENCES `modelofinal`.`COMPRA_ARTICULO` (`idFacturaCompraArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`USUARIO` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `NombreUsuario` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Empleado_idEmpleado`),
  INDEX `fk_Usuario_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Usuario_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `modelofinal`.`EMPLEADO` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`LIQUIDACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`LIQUIDACION` (
  `idLIQUIDACION` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NULL,
  `total_haberes_remunerativos` DOUBLE NULL,
  `total_haberes_no_remunerativos` VARCHAR(45) NULL,
  `total_retenciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idLIQUIDACION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`LIQUIDACION_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`LIQUIDACION_EMPLEADO` (
  `idLiquidacionEmpleado` INT NOT NULL AUTO_INCREMENT,
  `fecha_liquidacion` DATE NULL,
  `importe_neto` DOUBLE NULL,
  `total_haberes_remunerativos` DOUBLE NULL,
  `total_haberes_no_remunerativos` DOUBLE NULL,
  `total_retenciones` DOUBLE NULL,
  `total_bruto` DOUBLE NULL,
  `EMPLEADO_idEmpleado` INT NOT NULL,
  `inicio_periodo` DATE NULL,
  `fin_periodo` DATE NULL,
  `LIQUIDACION_idLIQUIDACION` INT NOT NULL,
  PRIMARY KEY (`idLiquidacionEmpleado`, `EMPLEADO_idEmpleado`, `LIQUIDACION_idLIQUIDACION`),
  INDEX `fk_LIQUIDACION_EMPLEADO_EMPLEADO1_idx` (`EMPLEADO_idEmpleado` ASC),
  INDEX `fk_LIQUIDACION_EMPLEADO_LIQUIDACION1_idx` (`LIQUIDACION_idLIQUIDACION` ASC),
  CONSTRAINT `fk_LIQUIDACION_EMPLEADO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_idEmpleado`)
    REFERENCES `modelofinal`.`EMPLEADO` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIQUIDACION_EMPLEADO_LIQUIDACION1`
    FOREIGN KEY (`LIQUIDACION_idLIQUIDACION`)
    REFERENCES `modelofinal`.`LIQUIDACION` (`idLIQUIDACION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`CONCEPTO_SUELDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`CONCEPTO_SUELDO` (
  `idCodigoConcepto` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `factor` FLOAT NULL,
  `tipo_concepto` ENUM('REMUNERATIVO', 'NO REMUNERATIVO', 'RETENCION') NULL,
  `tipo_cantidad` ENUM('PORCENTAJE', 'FIJO', 'UNIDAD') NULL,
  PRIMARY KEY (`idCodigoConcepto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`DETALLE_LIQUIDACION_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`DETALLE_LIQUIDACION_EMPLEADO` (
  `idDetalleLiquidacionEmpleado` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DOUBLE NULL,
  `LiquidacionEmpleado_idLiquidacionEmpleado` INT NOT NULL,
  `monto` DOUBLE NULL,
  `CONCEPTO_SUELDO_idCodigoConcepto` INT NOT NULL,
  PRIMARY KEY (`idDetalleLiquidacionEmpleado`, `LiquidacionEmpleado_idLiquidacionEmpleado`, `CONCEPTO_SUELDO_idCodigoConcepto`),
  INDEX `fk_DetalleLiquidacionEmpleado_LiquidacionEmpleado1_idx` (`LiquidacionEmpleado_idLiquidacionEmpleado` ASC),
  INDEX `fk_DETALLE_LIQUIDACION_EMPLEADO_CONCEPTO_SUELDO1_idx` (`CONCEPTO_SUELDO_idCodigoConcepto` ASC),
  CONSTRAINT `fk_DetalleLiquidacionEmpleado_LiquidacionEmpleado1`
    FOREIGN KEY (`LiquidacionEmpleado_idLiquidacionEmpleado`)
    REFERENCES `modelofinal`.`LIQUIDACION_EMPLEADO` (`idLiquidacionEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_LIQUIDACION_EMPLEADO_CONCEPTO_SUELDO1`
    FOREIGN KEY (`CONCEPTO_SUELDO_idCodigoConcepto`)
    REFERENCES `modelofinal`.`CONCEPTO_SUELDO` (`idCodigoConcepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`RECIBO_SUELDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`RECIBO_SUELDO` (
  `idRECIBO_SUELDO` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `total_neto` DOUBLE NULL,
  `LiquidacionEmpleado_idLiquidacionEmpleado` INT NOT NULL,
  PRIMARY KEY (`idRECIBO_SUELDO`, `LiquidacionEmpleado_idLiquidacionEmpleado`),
  INDEX `fk_RECIBO_SUELDO_LiquidacionEmpleado1_idx` (`LiquidacionEmpleado_idLiquidacionEmpleado` ASC),
  CONSTRAINT `fk_RECIBO_SUELDO_LiquidacionEmpleado1`
    FOREIGN KEY (`LiquidacionEmpleado_idLiquidacionEmpleado`)
    REFERENCES `modelofinal`.`LIQUIDACION_EMPLEADO` (`idLiquidacionEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`ACOPLADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`ACOPLADO` (
  `idAcoplado` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(45) NULL,
  `Patente` VARCHAR(45) NULL,
  `ChasisNumero` VARCHAR(17) NULL,
  PRIMARY KEY (`idAcoplado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`REMITO_HAS_ACOPLADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`REMITO_HAS_ACOPLADO` (
  `Remito_idRemito` INT NOT NULL,
  `Acoplado_idAcoplado` INT NOT NULL,
  PRIMARY KEY (`Remito_idRemito`, `Acoplado_idAcoplado`),
  INDEX `fk_Remito_has_Acoplado_Acoplado1_idx` (`Acoplado_idAcoplado` ASC),
  INDEX `fk_Remito_has_Acoplado_Remito1_idx` (`Remito_idRemito` ASC),
  CONSTRAINT `fk_Remito_has_Acoplado_Remito1`
    FOREIGN KEY (`Remito_idRemito`)
    REFERENCES `modelofinal`.`VIAJE` (`idRemito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Remito_has_Acoplado_Acoplado1`
    FOREIGN KEY (`Acoplado_idAcoplado`)
    REFERENCES `modelofinal`.`ACOPLADO` (`idAcoplado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelofinal`.`TIPO_LIQUIDACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelofinal`.`TIPO_LIQUIDACION` (
  `CATEGORIA_EMPLEADO_idCategoriaEmpleado` INT NOT NULL,
  `CONCEPTO_SUELDO_idCodigoConcepto` INT NOT NULL,
  PRIMARY KEY (`CATEGORIA_EMPLEADO_idCategoriaEmpleado`, `CONCEPTO_SUELDO_idCodigoConcepto`),
  INDEX `fk_CATEGORIA_EMPLEADO_has_CONCEPTO_SUELDO_CONCEPTO_SUELDO1_idx` (`CONCEPTO_SUELDO_idCodigoConcepto` ASC),
  INDEX `fk_CATEGORIA_EMPLEADO_has_CONCEPTO_SUELDO_CATEGORIA_EMPLEAD_idx` (`CATEGORIA_EMPLEADO_idCategoriaEmpleado` ASC),
  CONSTRAINT `fk_CATEGORIA_EMPLEADO_has_CONCEPTO_SUELDO_CATEGORIA_EMPLEADO1`
    FOREIGN KEY (`CATEGORIA_EMPLEADO_idCategoriaEmpleado`)
    REFERENCES `modelofinal`.`CATEGORIA_EMPLEADO` (`idCategoriaEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CATEGORIA_EMPLEADO_has_CONCEPTO_SUELDO_CONCEPTO_SUELDO1`
    FOREIGN KEY (`CONCEPTO_SUELDO_idCodigoConcepto`)
    REFERENCES `modelofinal`.`CONCEPTO_SUELDO` (`idCodigoConcepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
